HW5
b
i

Here we'll first fit the data on each label individually. Thus using Binary Relevance, once each label has been fit, we will predict over the test data and obtain predictions for each label using its corresponding classifier

Finally we'll merge predictions over each label into a 'prediction-matrix' and use that and compare it against the original test data outputs to obtain the hamming loss and the exact match parameters.

In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

In [2]:
df_train = pd.read_csv('Train_Data.csv',index_col=0)
df_test = pd.read_csv('Test_Data.csv',index_col=0)
print(df_train)
print(df_test)

      MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0          1.0  0.464912  0.409357  0.229967  0.043024  0.110648  0.041558   
1          1.0  0.550581  0.416760  0.199992  0.029394  0.152047  0.088736   
2          1.0  0.305720  0.161712  0.521877  0.148562 -0.035945 -0.138314   
3          1.0  0.085629  0.194640  0.558177  0.288138  0.013115 -0.084558   
4          1.0  0.157831  0.220788  0.662399  0.255485 -0.011588 -0.164573   
...        ...       ...       ...       ...       ...       ...       ...   
5031       1.0  0.948185  0.937043  0.430321  0.102723  0.398668 -0.067899   
5032       1.0  0.324665  0.231543  0.658007  0.202736 -0.012427 -0.089231   
5033       1.0  0.374609  0.134837  0.317741  0.105642  0.075624  0.158739   
5034       1.0  0.782845  0.885191  0.356826 -0.067459  0.240009  0.098551   
5035       1.0  0.044293  0.377297  0.421066  0.177453  0.209028  0.079516   

      MFCCs_ 8  MFCCs_ 9  MFCCs_10  ...  MFCCs_16  MFCCs_17  MF

In [3]:
features_train = df_train.drop(columns=['Family','Genus','Species'])
features_test = df_test.drop(columns=['Family','Genus','Species']) 

family_train = pd.DataFrame(df_train['Family'])
genus_train = pd.DataFrame(df_train['Genus'])
species_train = pd.DataFrame(df_train['Species'])

family_test = pd.DataFrame(df_test['Family'])
genus_test = pd.DataFrame(df_test['Genus'])
species_test = pd.DataFrame(df_test['Species'])

In [4]:
print(features_train)
print(features_test)

      MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0          1.0  0.464912  0.409357  0.229967  0.043024  0.110648  0.041558   
1          1.0  0.550581  0.416760  0.199992  0.029394  0.152047  0.088736   
2          1.0  0.305720  0.161712  0.521877  0.148562 -0.035945 -0.138314   
3          1.0  0.085629  0.194640  0.558177  0.288138  0.013115 -0.084558   
4          1.0  0.157831  0.220788  0.662399  0.255485 -0.011588 -0.164573   
...        ...       ...       ...       ...       ...       ...       ...   
5031       1.0  0.948185  0.937043  0.430321  0.102723  0.398668 -0.067899   
5032       1.0  0.324665  0.231543  0.658007  0.202736 -0.012427 -0.089231   
5033       1.0  0.374609  0.134837  0.317741  0.105642  0.075624  0.158739   
5034       1.0  0.782845  0.885191  0.356826 -0.067459  0.240009  0.098551   
5035       1.0  0.044293  0.377297  0.421066  0.177453  0.209028  0.079516   

      MFCCs_ 8  MFCCs_ 9  MFCCs_10  ...  MFCCs_13  MFCCs_14  MF

In [5]:
print(family_train)
print(genus_train)
print(species_train)

      Family
0          2
1          2
2          3
3          3
4          3
...      ...
5031       2
5032       3
5033       1
5034       2
5035       2

[5036 rows x 1 columns]
      Genus
0         3
1         3
2         0
3         0
4         0
...     ...
5031      3
5032      0
5033      1
5034      3
5035      3

[5036 rows x 1 columns]
      Species
0           5
1           5
2           1
3           1
4           1
...       ...
5031        5
5032        1
5033        2
5034        4
5035        5

[5036 rows x 1 columns]


In [6]:
print(family_test)
print(genus_test)
print(species_test)

      Family
0          1
1          2
2          3
3          3
4          3
...      ...
2154       3
2155       2
2156       2
2157       1
2158       2

[2159 rows x 1 columns]
      Genus
0         1
1         3
2         0
3         0
4         0
...     ...
2154      0
2155      7
2156      3
2157      1
2158      2

[2159 rows x 1 columns]
      Species
0           2
1           5
2           1
3           1
4           1
...       ...
2154        1
2155        9
2156        5
2157        2
2158        3

[2159 rows x 1 columns]


In [7]:
clf_fam = SVC().fit(features_train,family_train)
clf_gen = SVC().fit(features_train,genus_train)
clf_spe = SVC().fit(features_train,species_train)

C:\Users\DHRUV\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\DHRUV\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\DHRUV\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [8]:
family_predicted = clf_fam.predict(features_test)
print(family_predicted)                  # Predictions are not dataframes but arrays

[1 2 3 ... 2 1 2]


In [9]:
genus_predicted = clf_gen.predict(features_test)
print(genus_predicted)                  # Predictions are not dataframes but arrays

[1 3 0 ... 3 1 2]


In [10]:
species_predicted = clf_spe.predict(features_test)
print(species_predicted)                  # Predictions are not dataframes but arrays

[2 5 1 ... 5 2 3]


Collecting the predicted outputs and the test outputs into a dataframe for hamming and exact match calculations 

In [15]:
test_labels = pd.concat([family_test,genus_test,species_test],axis=1)
print(test_labels)

      Family  Genus  Species
0          1      1        2
1          2      3        5
2          3      0        1
3          3      0        1
4          3      0        1
...      ...    ...      ...
2154       3      0        1
2155       2      7        9
2156       2      3        5
2157       1      1        2
2158       2      2        3

[2159 rows x 3 columns]


In [16]:
predicted_test_labels = pd.concat([pd.DataFrame(family_predicted.transpose(), columns = ['Predicted Family']),
                                  pd.DataFrame(genus_predicted.transpose(), columns = ['Predicted Genus']),
                                  pd.DataFrame(species_predicted.transpose(), columns = ['Predicted Species'])],
                                  axis = 1)
print(predicted_test_labels)

      Predicted Family  Predicted Genus  Predicted Species
0                    1                1                  2
1                    2                3                  5
2                    3                0                  1
3                    3                0                  1
4                    3                0                  1
...                ...              ...                ...
2154                 3                0                  1
2155                 2                7                  9
2156                 2                3                  5
2157                 1                1                  2
2158                 2                2                  3

[2159 rows x 3 columns]


Exact Match Calculations

In [17]:
ex_mis = 0
for i in np.arange(0,test_labels.shape[0]):
    if ((predicted_test_labels.iloc[i,0] != test_labels.iloc[i,0]) or (predicted_test_labels.iloc[i,1] != test_labels.iloc[i,1]) or (predicted_test_labels.iloc[i,2] != test_labels.iloc[i,2])):
        ex_mis = ex_mis + 1

ex_mis_percentage = (ex_mis/test_labels.shape[0])*100

print('The exact mismatch in percentage is : \n',ex_mis_percentage,'%')
print('The exact match in percentage is : \n',100-ex_mis_percentage,'%')

The exact mismatch in percentage is : 
 2.7790643816581753 %
The exact match in percentage is : 
 97.22093561834183 %


Hamming Loss Calculations

In [18]:
hm_mis = 0
for i in np.arange(0,test_labels.shape[0]):
    for j in np.arange(0,test_labels.shape[1]):
        if predicted_test_labels.iloc[i,j] != test_labels.iloc[i,j]:
            hm_mis = hm_mis + 1

hm_mis_percentage = (hm_mis/test_labels.size)*100

print('The hamming loss mismatch in percentage is : \n',hm_mis_percentage,'%')
print('The hamming loss match in percentage is : \n',100-hm_mis_percentage,'%')

The hamming loss mismatch in percentage is : 
 1.6828778755596727 %
The hamming loss match in percentage is : 
 98.31712212444033 %


Hamming Loss
Hamming loss calculates mismatches (or matches) by calculating for each label the total mismatches, summing all such mismatches for all the labels.
Thus each prediction datapoint in a label and class matrix is compared to the corresponding datapoint to calculate mismatches

So hamming loss calculates mismatches over extended labels, like traditional test errors by stacking prediction and test labels correspondingly over one another and calculating the mismatches.

Thus for hamming loss entry wise comparison takes place

Exact Match
Exact match, checks, as obvious, the exact label string matches on our prediction to our test. Thus each sample has a set of labels with classes in each. If for a sample all the classes in all the labels predicted match the test sample label and classes, only then, the match is true. If even a single label for a sample is predicted incorrectly, the sample is assumed to be mismatched. Thus exact match calculates matches over a given row, along all the columns.

Obviously it is expected that exact match give a larger mismatch than hamming loss as the conditions for exact match are much more rigid/strict than for hamming loss.


This is the difference between Hamming Loss and Exact Match